
version: '3'
services:
  postgres:
    image: postgres:13
    container_name: database
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./database/pg:/var/lib/postgresql
      - ./database/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
